use super::model::{BenchmarkScenario, RankingTier, RepoCandidate};

pub fn default_scenarios() -> Vec<BenchmarkScenario> {
    vec![
        BenchmarkScenario {
            scenario_id: "core_rag_foundation".to_string(),
            description: "Core milestone planning for a LlamaIndex-based RAG stack.".to_string(),
            tier: RankingTier::CoreMilestone,
            top_n: 3,
            expected_top_repos: repos(&[
                "github.com/run-llama/llama_index",
                "github.com/langchain-ai/langchain",
                "github.com/chroma-core/chroma",
            ]),
            candidates: vec![
                RepoCandidate::new(
                    "github.com/run-llama/llama_index",
                    "llama-index",
                    0,
                    0.88,
                    2,
                    0.95,
                    180,
                    2_200,
                ),
                RepoCandidate::new(
                    "github.com/langchain-ai/langchain",
                    "langchain",
                    1,
                    0.73,
                    1,
                    0.93,
                    160,
                    1_800,
                ),
                RepoCandidate::new(
                    "github.com/chroma-core/chroma",
                    "chromadb",
                    1,
                    0.67,
                    4,
                    0.89,
                    190,
                    1_700,
                ),
                RepoCandidate::new(
                    "github.com/pydantic/pydantic",
                    "pydantic",
                    2,
                    0.20,
                    1,
                    0.98,
                    70,
                    500,
                ),
                RepoCandidate::new(
                    "github.com/python/cpython",
                    "json",
                    3,
                    0.04,
                    1,
                    0.99,
                    210,
                    3_200,
                ),
                RepoCandidate::new(
                    "github.com/psf/requests",
                    "requests",
                    2,
                    0.11,
                    6,
                    0.96,
                    110,
                    800,
                ),
            ],
        },
        BenchmarkScenario {
            scenario_id: "feature_vectorstore_bug".to_string(),
            description: "Feature-level bug in vector store retrieval integration.".to_string(),
            tier: RankingTier::Feature,
            top_n: 2,
            expected_top_repos: repos(&[
                "github.com/run-llama/llama_index",
                "github.com/chroma-core/chroma",
            ]),
            candidates: vec![
                RepoCandidate::new(
                    "github.com/run-llama/llama_index",
                    "llama-index",
                    0,
                    0.86,
                    3,
                    0.95,
                    170,
                    2_000,
                ),
                RepoCandidate::new(
                    "github.com/chroma-core/chroma",
                    "chromadb",
                    1,
                    0.82,
                    2,
                    0.90,
                    165,
                    1_600,
                ),
                RepoCandidate::new(
                    "github.com/community-forks/llama_index-hotfix",
                    "llama-index-hotfix",
                    0,
                    0.92,
                    0,
                    0.35,
                    140,
                    1_400,
                ),
                RepoCandidate::new(
                    "github.com/langchain-ai/langchain",
                    "langchain",
                    1,
                    0.62,
                    1,
                    0.93,
                    155,
                    1_700,
                ),
                RepoCandidate::new(
                    "github.com/python/cpython",
                    "json",
                    3,
                    0.03,
                    1,
                    0.99,
                    210,
                    3_200,
                ),
            ],
        },
        BenchmarkScenario {
            scenario_id: "task_prompt_regression".to_string(),
            description: "Task-level prompt assembly regression during agent execution."
                .to_string(),
            tier: RankingTier::TaskChatSubagent,
            top_n: 2,
            expected_top_repos: repos(&[
                "github.com/run-llama/llama_index",
                "github.com/langchain-ai/langchain",
            ]),
            candidates: vec![
                RepoCandidate::new(
                    "github.com/run-llama/llama_index",
                    "llama-index",
                    0,
                    0.81,
                    2,
                    0.95,
                    120,
                    900,
                ),
                RepoCandidate::new(
                    "github.com/langchain-ai/langchain",
                    "langchain",
                    1,
                    0.79,
                    1,
                    0.93,
                    130,
                    980,
                ),
                RepoCandidate::new(
                    "github.com/openai/openai-python",
                    "openai",
                    2,
                    0.56,
                    1,
                    0.91,
                    115,
                    800,
                ),
                RepoCandidate::new(
                    "github.com/python/cpython",
                    "json",
                    3,
                    0.07,
                    1,
                    0.99,
                    210,
                    3_200,
                ),
                RepoCandidate::new(
                    "github.com/psf/requests",
                    "requests",
                    2,
                    0.12,
                    3,
                    0.96,
                    100,
                    700,
                ),
            ],
        },
        BenchmarkScenario {
            scenario_id: "rare_json_edge_case".to_string(),
            description: "Rare runtime edge case tied to Python JSON internals.".to_string(),
            tier: RankingTier::TaskChatSubagent,
            top_n: 1,
            expected_top_repos: repos(&["github.com/python/cpython"]),
            candidates: vec![
                RepoCandidate::new(
                    "github.com/python/cpython",
                    "json",
                    3,
                    0.95,
                    0,
                    0.99,
                    220,
                    3_300,
                ),
                RepoCandidate::new(
                    "github.com/run-llama/llama_index",
                    "llama-index",
                    0,
                    0.12,
                    2,
                    0.95,
                    130,
                    1_000,
                ),
                RepoCandidate::new(
                    "github.com/orjson/orjson",
                    "orjson",
                    2,
                    0.59,
                    7,
                    0.88,
                    140,
                    1_100,
                ),
                RepoCandidate::new(
                    "github.com/psf/requests",
                    "requests",
                    2,
                    0.08,
                    3,
                    0.96,
                    100,
                    700,
                ),
            ],
        },
    ]
}

fn repos(values: &[&str]) -> Vec<String> {
    values.iter().map(|value| value.to_string()).collect()
}
